[package]
name = "rq-ring"
version = "0.1.0"
edition = "2024"

[dependencies]
crystals-dilithium = "1.0.0"
rand = "0.8"
num-modular = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2.19"

